<?php

function gcal_node_insert($node) {
	if($node->type == 'event') {
		drupal_set_message('test');
		$path = drupal_get_path('module', 'gcal');
		require_once($path . '/api/src/apiClient.php');
		require_once($path . '/api/src/contrib/apiCalendarService.php');

		$apiClient = new apiClient();
		$apiClient->setUseObjects(true);
		$service = new apiCalendarService($apiClient);

		if (isset($_SESSION['oauth_access_token'])) {
		  $apiClient->setAccessToken($_SESSION['oauth_access_token']);
		} else {
		  $token = $apiClient->authenticate();
		  $_SESSION['oauth_access_token'] = $token;
		}



		drupal_set_message($createdEvent->getId());
	}
}